/*
 * Copyright (C) 2026 The PureDarwin Project, All rights reserved.
 *
 * @LICENSE_HEADER_BEGIN@
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * @LICENSE_HEADER_END@
 */

#include <rsplib/base.hpp>
#include <rsplib/aesvs.hpp>
#include <rsplib/osl.hpp>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>

using namespace corecrypto::rsplib;
using namespace corecrypto;

parser::parser(const std::string &basename, std::stringstream &stream)
{
    osl::log(osl::debug, "parser::parser enter >>");
    _basename = basename;
    //
    // RSP headers usually have a marker at the beginning.
    //
    std::string line;

    while (std::getline(stream, line)) {
        osl::log(osl::debug, "parser: cur line: %s", line.c_str());
        if (line.find("AESVS") != std::string::npos) {
            if (line.find("ECB") == std::string::npos) {
                parse_aesvs(stream, false);
            } else {
                parse_aesvs(stream, true);
            }
            break;
        } else if (line.find("SHA") != std::string::npos) {
            parse_shavs(stream);
        }
    }
    osl::log(osl::debug, "parser::parser exit <<");
}

void parser::write_header(std::stringstream &stream)
{
    stream << "/*" << std::endl;
    stream << " * Copyright (C) 2026 The PureDarwin Project, All rights reserved." << std::endl;
    stream << " * " << std::endl;
    stream << " * @LICENSE_HEADER_BEGIN@" << std::endl;
    stream << " * Licensed under the Apache License, Version 2.0 (the \"License\");" << std::endl;
    stream << " * you may not use this file except in compliance with the License." << std::endl;
    stream << " * You may obtain a copy of the License at" << std::endl;
    stream << " * " << std::endl;
    stream << " *     http://www.apache.org/licenses/LICENSE-2.0" << std::endl;
    stream << " * " << std::endl;
    stream << " * Unless required by applicable law or agreed to in writing, software" << std::endl;
    stream << " * distributed under the License is distributed on an \"AS IS\" BASIS," << std::endl;
    stream << " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied." << std::endl;
    stream << " * See the License for the specific language governing permissions and" << std::endl;
    stream << " * limitations under the License." << std::endl;
    stream << " * @LICENSE_HEADER_END@" << std::endl;
    stream << " */" << std::endl;
    stream << std::endl;
    stream << "//" << std::endl;
    stream << "// THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY RSPLIB" << std::endl;
    stream << "//" << std::endl;
    stream << std::endl;
}

//
// this is for converged tests.
//
void parser::write_tests_to_stream(std::stringstream &stream) {
    write_header(stream);
    for (int i = 0; i < _tests.size(); i++) {
        _tests[i]->write_to_stream(stream);
        stream << std::endl;
    }
}

//
// this completely ignores the -o flag in rsp2header
//
void parser::write_tests_to_directory(std::filesystem::path &path)
{
    osl::log(osl::debug, "parser: writing to directory >>");
    for (int i = 0; i < _tests.size(); i++) {
        std::filesystem::path ofpath = path.u8string();
        ofpath /= _tests[i]->get_name() + ".inc";
        std::fstream outstream;
        osl::log(osl::debug, "parser: %s", ofpath.u8string().c_str());
        outstream.open(ofpath, std::fstream::out);
        std::stringstream stream;
        write_header(stream);
        _tests[i]->write_to_stream(stream);
        outstream << stream.str();
        outstream.close();
    }
}
