"""
Copyright (C) 2025-2026 The PureDarwin Project, All rights reserved.

@LICENSE_HEADER_BEGIN@
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
@LICENSE_HEADER_END@
"""
 
import argparse

parser = argparse.ArgumentParser(
    prog="rsp_parser", description="A basic parser for the NIST's RSP files."
)

parser.add_argument("-f", "--file", required=True)

result = []

result.append("// Copyright (C) 2025-2026 The PureDarwin Project, All rights reserved.")
result.append("// This file has been autogenerated by rsp_parser.")

# This is going to get very big. very quickly.

def parse_rsp(rsp):
    aesvsmode = False

    for line in rsp:
        if "AESVS" in line:
            # aes validation line...
            aesvsmode = True
        else:
            if aesvsmode == True:
                if "[ENCRYPT]" in line:
                    break


def main():
    args = parser.parse_args()
    path = args.file

    # ugh, it spits and error at me :(
    with open(path, "r") as f:
        lines = f.readlines()
        parse_rsp(lines)



if __name__ == "__main__":
    main()
