name: corecrypto (Darwin)

on:
  workflow_dispatch:
    branches:
      - development
      - master

  push:
    branches:
      - development
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone Sources
        run: |
          git clone --branch ${GITHUB_REF_NAME} https://github.com/${{ github.repository }} ~/corecrypto
      - name: Build & Install
        run: |
          cd ~/corecrypto
          xcodebuild install -target corecrypto_darwin DSTROOT=$PWD/DSTROOT
      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v6
        with:
          name: corecrypto
          path: /Users/runner/corecrypto/DSTROOT/
